secrets:
  auth_key:
    file: /data/docker/secrets/tailscale-brett/auth.key
services:
  tailscale-brett:
    image: tailscale/tailscale:latest
    container_name: tailscale-brett
    hostname: tailscale-brett-exit-node
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    environment:
      - TS_AUTHKEY_FILE=/run/secrets/auth_key
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_ACCEPT_DNS=true
      - TS_AUTH_ONCE=true
      - TS_ROUTES=192.168.10.0/24
    network_mode: host
    volumes:
      - /data/docker/mounts/tailscale-brett/tailscale-state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
    secrets:
      - auth_key
    restart: unless-stopped
