# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2048M
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "30053:80/tcp"
      - "30453:443/tcp"
    environment:
      TZ: 'Australia/Melbourne'
      FTLCONF_webserver_api_password: ''
      FTLCONF_dns_listeningMode: 'ALL'
      FTLCONF_misc_etc_dnsmasq_d: 'true'
    volumes:
      - '/data/docker/mounts/pihole/config:/etc/pihole'
      - '/data/docker/mounts/pihole/dnsmasq:/etc/dnsmasq.d'
    cap_add:
      - SYS_NICE
      - CAP_SYS_TIME
    restart: unless-stopped
    networks:
      - pihole-net

  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:latest
    ports:
      - "9617:9617"
    environment:
      # Use internal Docker networking to reach Pi-hole via its service name
      - PIHOLE_HOSTNAME=http://pihole
      # Required flag enabling the exporter to process Pi-hole v6 API structure
      - PIHOLE_VERSION=v6
      - PIHOLE_PASSWORD=${EXPORTER_APP_PASSWORD}
    restart: unless-stopped
    depends_on:
      - pihole
    networks:
      - pihole-net

networks:
  pihole-net:
    driver: bridge
