services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.emporer.net/
    ports:
      - '3000:3000'
    volumes:
      - /data/docker/mounts/grafana:/var/lib/grafana
    user: '1000:1000'
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - '9090:9090'
    volumes:
      - /data/docker/configs/grafana/prometheus.yml:/etc/prometheus/prometheus.yml
    user: '1000:1000'
    networks:
      - monitoring
    restart: unless-stopped