services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.emporer.net/
    ports:
      - '3000:3000'
    volumes:
      - /data/docker/mounts/grafana:/var/lib/grafana
    user: '1000:1000'
    restart: unless-stopped