global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'nginx-proxy-manager'
    static_configs:
      - targets: ['nginx.emporer.net:9113']
  - job_name: 'glances'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.10.4:9091']
  - job_name: 'pihole'
    static_configs:
      - targets: ['192.168.10.4:9617']
        labels:
          instance: 'primary'
      - targets: ['192.168.10.5:9617']
        labels:
          instance: 'secondary'