services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    ports:
      - '80:80'
      - '443:443'
      - '30020:81' # Admin Web UI
    environment:
      TZ: "Australia/Melbourne"
      DISABLE_IPV6: 'true'
    volumes:
      - /data/docker/mounts/nginx/data:/data
      - /data/docker/mounts/nginx/certs:/etc/letsencrypt
    restart: unless-stopped