services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    ports:
      - "31050:3001"
    volumes:
      - /data/docker/mounts/uptime-kuma/data:/app/data
    environment:
      - TZ=Australia/Melbourne
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      interval: 30s
      retries: 3
      start_period: 10s
      timeout: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped